### ISSUE TITLE
Is there any code for visualise the demo?

### ISSUE THREAD

**Issue by SalemAmeen** [clementfarabet/manifold#11]
I tried the demo and it works but I received this error at the end, I think, it might be related to gfx.

This is the error

Successfully performed t-SNE in 0.33333206176758 seconds.
qlua: /usr/local/share/lua/5.1/gfx/js.lua:279: dataset.values could not be parsed
stack traceback:
	[C]: at 0x010cb841d0
	[C]: in function 'error'
	/usr/local/share/lua/5.1/gfx/js.lua:279: in function 'format'
	/usr/local/share/lua/5.1/gfx/js.lua:359: in function 'chart'
	demo_tsne.lua:27: in function 'show_scatter_plot'
	demo_tsne.lua:72: in function 'demo_tsne'
	demo_tsne.lua:86: in main chunk
Lua 5.1  Copyright (C) 1994-2008 Lua.org, PUC-Rio

However, I tried MATLAB version and 100% works with me. Is there any modification so that the code works with itorch or qlua.

Thanks in advance.

**Comment by lvdmaaten** [comment]
I just tried to run the demo and I could not reproduce this issue. Are you sure you have gfx.js installed and that you call the demo script with `th -x demo_tsne.lua`? This looks more like an issue with the `gfx.js` package than with the `manifold` demos.
